export const PENDU_WORDS = [
  "ORDINATEUR", "RESEAU", "CAMEROUN", "TECHNICIEN", "SERVEUR",
  "CLAVIER", "IMPRIMANTE", "LOGICIEL", "CYBERSECURITE", "INTERNET",
  "TELEPHONE", "MARKETPLACE", "FREELANCE", "INNOVATION", "DOUALA",
];

export const PENDU_ALPHABET = "AZERTYUIOPQSDFGHJKLMWXCVBN".split("");
export const PENDU_MAX_ERRORS = 7;
